### ISSUE TITLE
uuid1() always return an uuid with 000000000000 in the last group

### ISSUE THREAD

**Issue by thanh-taro** [ramsey/uuid#133]
In my code, I just use uuid1()->toString() and it always return an uuid with 000000000000 in the last group. For example:

```
07230db8-6e55-11e6-b7f6-000000000000
```

I'm using PHP7, Ubuntu 14.04 64bit.

**Comment by ramsey** [comment]
What version of ramsey/uuid? Can you provide a longer code example of the code you are using that produces this?

Thanks!

**Comment by thanh-taro** [comment]
I'm using version `3.5.0` with Laravel 5.2. I add an alias
```php
'UUID' => Ramsey\Uuid\Uuid::class 
```
And the code is very simple
```php
echo \UUID::uuid1()->toString();
```

**Comment by thanh-taro** [comment]
In my local host, it works well without any issue. But, when I deploy to the server, I always returns an uuid with `000000000000`.

**Comment by thanh-taro** [comment]
Any help?

**Comment by ramsey** [comment]
Sorry. I'm UTC-5, so it was late last night when I received your message. :-)

Can you run the following script on your server? Which provider appears to be generating the `000000000000` value?

``` php
<?php

require_once 'vendor/autoload.php';

use Ramsey\Uuid\Uuid;
use Ramsey\Uuid\Provider\Node\RandomNodeProvider;
use Ramsey\Uuid\Provider\Node\SystemNodeProvider;

echo Uuid::uuid1()->toString() . "\n";

echo get_class(Uuid::getFactory()->getNodeProvider())
    . ': ' . Uuid::getFactory()->getNodeProvider()->getNode()
    . "\n";

$randomProvider = new RandomNodeProvider();
echo 'RandomNodeProvider: ' . $randomProvider->getNode() . "\n";

$systemProvider = new SystemNodeProvider();
echo 'SystemNodeProvider: ' . $systemProvider->getNode() . "\n";
```

**Comment by thanh-taro** [comment]
Oh, I'm UTC +7. So far. :D 
Let me run your code.

**Comment by thanh-taro** [comment]
This is the result:
```
62adc6f6-6f1c-11e6-9b36-000000000000
Ramsey\Uuid\Provider\Node\FallbackNodeProvider: 000000000000
RandomNodeProvider: 19645b6adbcd
SystemNodeProvider: 000000000000
```

**Comment by ramsey** [comment]
It sounds like your server's MAC address is all 0s.

This might be relevant: http://askubuntu.com/questions/74575/what-should-my-mac-address-be-now-shows-000000000000

If you run `netstat -ie` from the command line you should see an interface table. Don't paste the output here, but is the first `HWaddr` in that table `00:00:00:00:00:00`? If so, that's why UUID version 1 is giving you all 0s for the node.

Is the first interface in that table `eth0`? If not, what is it? If it's something else, maybe ramsey/uuid can somehow do a better job of finding the correct network interface MAC address to use.

**Comment by thanh-taro** [comment]
This command give me the result with all the `HWaddr` is `00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00`. Poor me. I think the reason is my server. You can close this issue by now.

Thank you. You are a good man. :D

**Comment by ramsey** [comment]
No worries. Glad to help. :-)
