### ISSUE TITLE
Extending Uuid seems impossible

### ISSUE THREAD

**Issue by fedpet** [ramsey/uuid#141]
Excuse me, maybe it's late and i'm blind but to me it seems almost impossible..

```
class MyUuid extends \Ramsey\Uuid\Uuid {
    public function toString()
    {
        return 'test';
    }
}
class MyUuidBuilder extends \Ramsey\Uuid\Builder\DefaultUuidBuilder {
    public function build(\Ramsey\Uuid\Codec\CodecInterface $codec, array $fields)
    {
        return new MyUuid($fields, $this->converter, $codec);
    }
}

$factory = \Ramsey\Uuid\Uuid::getFactory();
$factory->setUuidBuilder(new MyUuidBuilder($factory->getNumberConverter()));
\Ramsey\Uuid\Uuid::setFactory($factory); // just to be sure

var_dump(\Ramsey\Uuid\Uuid::fromBytes($data));
```

the custom builder is never called.

the only way I can think of it is extending the entire Uuid class and overriding every static method..

am I missing something?

thanks

p.s.
the ultimate goal (for now) is just providing a Uuid which json_serializes in hex (with getHex instead of toString)

**Comment by ramsey** [comment]
The issue you are facing is a result of the Uuid class acting as a proxy to methods on a UuidFactory object. When you call the static method `Uuid::fromBytes()`, it calls `fromBytes()` on the factory, which is using the default codec to decode the bytes. It gets the default codec (which is configured with the default builder) from the default FeatureSet when you instantiate the UuidFactory.

There are several ways around this. Here's one way:

``` php
class MyUuid extends \Ramsey\Uuid\Uuid
{
    public function toString()
    {
        return 'test';
    }
}

class MyUuidBuilder implements \Ramsey\Uuid\Builder\UuidBuilderInterface
{
    protected $converter;

    public function __construct(\Ramsey\Uuid\Converter\NumberConverterInterface $converter)
    {
        $this->converter = $converter;
    }

    public function build(\Ramsey\Uuid\Codec\CodecInterface $codec, array $fields)
    {
        return new MyUuid($fields, $this->converter, $codec);
    }
}

$factory = new \Ramsey\Uuid\UuidFactory();

$builder = new MyUuidBuilder($factory->getNumberConverter());
$codec = new \Ramsey\Uuid\Codec\StringCodec($builder);

$factory->setUuidBuilder($builder);
$factory->setCodec($codec);
\Ramsey\Uuid\Uuid::setFactory($factory);

$base64Bytes = 'tBXqB39LRKmq5kKhYB57kA==';

$myUuid = \Ramsey\Uuid\Uuid::fromBytes(base64_decode($base64Bytes));

echo $myUuid;
```

If you extend from DefaultUuidBuilder, you won't have access to `$this->converter`, since it's a `private` property. This is done on purpose. Since it's a simple interface, we make public only what the interface requires; not all builders will require the number converter passed to it in the same way (or at all).

You also don't need to set the factory on the static Uuid class. You may use the factory directly, which might be preferrable to the magic of static classes/methods:

``` php
$myUuid = $factory->fromBytes(base64_decode($base64Bytes));
```

Now, this accomplishes exactly what you're trying to do in your example, but to accomplish your goal, I would do this:

``` php
class MyUuid extends \Ramsey\Uuid\Uuid
{
    public function jsonSerialize()
    {
        return $this->getHex();
    }
}

class MyUuidBuilder implements \Ramsey\Uuid\Builder\UuidBuilderInterface
{
    protected $converter;

    public function __construct(\Ramsey\Uuid\Converter\NumberConverterInterface $converter)
    {
        $this->converter = $converter;
    }

    public function build(\Ramsey\Uuid\Codec\CodecInterface $codec, array $fields)
    {
        return new MyUuid($fields, $this->converter, $codec);
    }
}

$factory = new \Ramsey\Uuid\UuidFactory();

$builder = new MyUuidBuilder($factory->getNumberConverter());
$codec = new \Ramsey\Uuid\Codec\StringCodec($builder);

$factory->setUuidBuilder($builder);
$factory->setCodec($codec);

$base64Bytes = 'tBXqB39LRKmq5kKhYB57kA==';

$myUuid = $factory->fromBytes(base64_decode($base64Bytes));

echo json_encode($myUuid);
```

It's somewhat round-about, I'll grant you, but there's a lot of flexibility in this approach.

Hope this helps!

**Comment by fedpet** [comment]
thank you very much for the support
