### ISSUE TITLE
Can two systems generate repeated UUIDs?

### ISSUE THREAD

**Issue by MrVokia** [ramsey/uuid#148]
If I have two systems have used the uuid, then there will be repeated uuid generation?

**Comment by ramsey** [comment]
@MrVokia You *should not* see repeated UUIDs if generating on multiple systems. The probability of generating duplicate version 4 (random) UUIDs is very high ([see Wikipedia's entry](https://en.wikipedia.org/wiki/Universally_unique_identifier#Random_UUID_probability_of_duplicates)). 

However, we did run into a case where the same machine was generating duplicates due to a threading issue with OpenSSL. This issue is [described on my blog](https://benramsey.com/blog/2016/04/ramsey-uuid/#when-uuids-collide). If you're using ramsey/uuid 3.3.0 or greater, then you should be fine.

Do you have a problem where UUIDs are being repeated? If so, can you show some example code?

**Comment by MrVokia** [comment]
very high? @ramsey

**Comment by ramsey** [comment]
Oops! I meant low. Very, very low. Sorry about that.
