### ISSUE TITLE
When calling on a 32-bit system, BigNumber must be present.

### ISSUE THREAD

**Issue by JustClear** [ramsey/uuid#153]
When I calling a api request, postman give me some error.

`When calling Ramsey\\Uuid\\Converter\\Time\\DegradedTimeConverter::calculateTime on a 32-bit system, Moontoast\\Math\\BigNumber must be present.`

**Comment by ramsey** [comment]
This is correct. Some of the math involved when dealing with UUIDs is impossible on 32-bit systems. This is because a UUID is an unsigned 128-bit integer, and the time portion of a version 1 UUID is an unsigned 64-bit number. PHP on a 32-bit system only supports signed integers up to `2147483647`.

Installing the moontoast/math library should fix your issue:

```
composer require moontoast/math
```

Thanks!

**Comment by JustClear** [comment]
It's working now ! Thanks for your help !!! 🎉🎉🎉🎉
But there's another problem that bothers me, that is the PHP I used was running on 64-bit system(Windows), PHP version is 5.6.

**Comment by ramsey** [comment]
I must have misunderstood. I thought you were running PHP on a 32-but system. You’re on a 64-bit system?

The exception message is badly worded, then, but it’s still correct (sort of). PHP only supports signed integers, but the time field of a UUID is an unsigned 64-bit integer, so it’s double the max number allowed by a signed 64-bit integer and overflows on PHP. That’s why moontoast/math is still needed.

I’ll update the exception message so that it’s less confusing.

**Comment by VivekShingala** [comment]
Thank you very much. Installing moontoast/math helped me to fix the issue.

composer require moontoast/math
