### ISSUE TITLE
Change Codecs (Documentation)

### ISSUE THREAD

**Issue by juliusstoerrle** [ramsey/uuid#154]
Hi, I would like to use ordered UUIDs (v1).

I know that there is a Codec doing that and I know the Codec is set by a FeatureSet given to a UuidFactory constructor.

but how do I create a FeatureSet with a different Codec than the standard StringCodec?
Is there any method to set the Codec? I could't find one.

Thanks for your help in advance.

If someone tells me how to do handle this. I would be happy to write a wiki page about it!

**Comment by ramsey** [comment]
I have a presentation that shows some of the ways to use alternate codecs. Starting at slide 46, you can see examples using different codecs. The `OrderedTimeCodec` starts at slide 61.

* https://benramsey.com/talks/2016/11/tnphp-uuid/

As you can see in the examples, I'm using the factory directly. For example:

``` php
$factory = new UuidFactory();

$codec = new OrderedTimeCodec(
    $factory->getUuidBuilder()
);

$factory->setCodec($codec);

$orderedTimeUuid = $factory->uuid1();
```

However, if you'd like to replace the default factory so that calling `Uuid::uuid1()` uses it, you may do something like this:

``` php
Uuid::setFactory($factory);

$orderedTimeUuid = Uuid::uuid1();
```

Please feel free to contribute to the wiki! It's definitely lacking in examples of how to use these other features. Thanks!

**Comment by juliusstoerrle** [comment]
Thanks for your help. I think its a really nice implementation of the suggestions from the Percona blog.
I'm not a native English speaker, so there might be some errors on the wiki page.
