### ISSUE TITLE
laravel 5.4

### ISSUE THREAD

**Issue by Marielleaj** [ramsey/uuid#157]
i can install in on laravel 5.4 why this is happening?

**Comment by ramsey** [comment]
Can you paste the error message received when you try to install ramsey/uuid?

**Comment by Marielleaj** [comment]
Using version ^3.5 for ramsey/uuid
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for barryvdh/laravel-migration-generator dev-master -> satisfiable by barryvdh/laravel-migration-generator[dev-master].
    - Conclusion: remove laravel/framework v5.4.15
    - Conclusion: don't install laravel/framework v5.4.15
    - barryvdh/laravel-migration-generator dev-master requires illuminate/support ~4 -> satisfiable by illuminate/support[v4.0.0, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.13, v4.1.14, v4.1.15, v4.1.16, v4.1.17, v4.1.18, v4.1.19, v4.1.2, v4.1.20, v4.1.21, v4.1.22, v4.1.23, v4.1.24, v4.1.25, v4.1.26, v4.1.27, v4.1.28, v4.1.29, v4.1.3, v4.1.30, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - don't install illuminate/support v4.0.0|don't install laravel/framework v5.4.15

**Comment by ramsey** [comment]
The solution to the problem you have is described in the output you pasted.

You're trying to install barryvdh/laravel-migration-generator at `dev-master`, while you already have laravel/framework at `v5.4.15` installed. This creates a conflict, since the barryvdh/laravel-migration-generator package [requires illuminate/support at version `~4`](https://packagist.org/packages/barryvdh/laravel-migration-generator), but you already have illuminate/support installed at version 5.4.15 (illuminate/support is provided by laravel/framework). So, Composer is unable to install barryvdh/laravel-migration-generator because it cannot satisfy its requirements.

You either won't be able to use barryvdh/laravel-migration-generator, or you'll need to use Laravel version 4, instead of Laravel 5.

This isn't an issue with ramsey/uuid.
