### ISSUE TITLE
FeatureSet::hasBigNumber generates a warning when moontoast/bignumber is not installed

### ISSUE THREAD

**Issue by dotboris** [ramsey/uuid#169]
I've recently started using this lib in a project of mine. Ever since, I've been getting warnings:

```
include(Moontoast\Math\BigNumber.php): File not found

/builds/composer/pmc-realex/vendor/magento/core/lib/Varien/Autoload.php:94
/builds/composer/pmc-realex/vendor/ramsey/uuid/src/FeatureSet.php:321
/builds/composer/pmc-realex/vendor/ramsey/uuid/src/FeatureSet.php:244
/builds/composer/pmc-realex/vendor/ramsey/uuid/src/FeatureSet.php:124
/builds/composer/pmc-realex/vendor/ramsey/uuid/src/UuidFactory.php:63
/builds/composer/pmc-realex/vendor/ramsey/uuid/src/Uuid.php:569
/builds/composer/pmc-realex/vendor/ramsey/uuid/src/Uuid.php:674
/builds/composer/pmc-realex/src/app/code/local/PMC/Realex/controllers/AuthorizeController.php:36
/builds/composer/pmc-realex/test/AuthorizeControllerTest.php:50
```

Note that this in the context of a unit test. This warning causes my test to fail.

I've done some digging and I've managed to pinpoint the issue to https://github.com/ramsey/uuid/blob/master/src/FeatureSet.php#L321

My understanding is that during the initialization of the `FeatureSet` the `hasBigNumber` method is called. This method calls `class_exists('Moontoast\Math\BigNumber')`. This causes php's autoload feature to kick in.

One of the registered autoloaders (Magento's [`Varien_Autoload`](https://github.com/firegento/magento/blob/magento-1.9.2.4/lib/Varien/Autoload.php#L77-L95) to be specific) generates a path for the class and blindly includes that path. Since the path does not exist, a warning is generated.

In theory, any autoloader that isn't too careful about generating warnings will systematically generate warnings when this lib is being used.

**Comment by ramsey** [comment]
I'm not sure how to best handle this. If the autoloader attempts to blinding include the file when it is invoked with `class_exists()`, then the `class_exists()` function has no real value. I can't depend on it to return `true` or `false` in other environments without emitting any warnings.

Ideally, `Varien_Autoload` should use `file_exists()` before blinding including the file, but I can't force them to do that. Since this library shouldn't assume any details about the environment in which it's being used, I can't reliably construct a file path and test for the existence of the file. `class_exists()` is my only reliable option.

I might be able to suppress the warning by using the error-suppression operator (`@`), but that feels dirty. :smile:

Thoughts?

**Comment by dotboris** [comment]
I think that this is really a bug in magento's autoload implementation and not your lib. I would just close this.

Since I wrote this issue, I have patched mangento's autoload not to generate a warning. I don't have this issue anymore.

**Comment by ramsey** [comment]
Sorry for the delay in responding. I'm not sure how I missed this. :smile:

**Comment by githoober** [comment]
Can't class_exists be simply called like this?

class_exists($className, false)?
