### ISSUE TITLE
File/Foldernames dashed or undashed ? (same as for URL actually)

### ISSUE THREAD

**Issue by Yamakasi** [ramsey/uuid#174]
I wonder if it's better to use undashed UUID's for files and foldernames and really when you use them in browsers, html, or whatever.

I like UUID's but the dashes make very clear you use UUID's... not that it's a problem you use them and people can see it, but is undashed nicer in webcases and file storage ?

I ask this because the UUID RFC actually says... dash it!

**Comment by ramsey** [comment]
Originally, I had thought this question was about using dashed vs. un-dashed UUIDs in a database, so I was giving a lot of thought to prepare an answer about that. :smile:

I can't say whether it's _better_ or _worse_ to use dashes in UUIDs in filenames, folder names, or URLs. I don't think there are any best practices for this, so it's up to you. You're using the UUID to uniquely identify content in your system, so as long as you're able to use the UUID to look up information in your application, then all should be good.

Cheers!

**Comment by Yamakasi** [comment]
Thanks for the update! 

I'm really looking at native stuff and you mention something very important... storage in a database... they should be dashed in your opinion, maybe because the internal UUID function MySQL has ?

**Comment by ramsey** [comment]
In a database, my opinion is to store them in a `CHAR(16)` field in binary format. I also advise against using them as primary keys, since it will greatly increase the size of your database; PKs are combined with all other keys on a table, so the more storage required by a PK, the larger the keys will be. That said, place an index on your UUID field, so that lookups are fast.

**Comment by Yamakasi** [comment]
OK, thanks! I'm not sure about the binary, I see lots of good performance about doing so but for 10 million records you only save 150MB.

UUID's should indeed not be set as PK, better have an AutoIncrement which is PK next to it. About the index is what I need to read about, thanks for that tip!

So you would do dashed it seems, which combines with the CHAR(16) in perfect size.

Do you let you PHP query handle the binary in that case or do it in code ?

**Comment by ramsey** [comment]
If you do dashed, you would need `CHAR(36)`, since a string representation of UUID with dashes is 36 characters. A binary representation UUID is 16 bytes. Binary doesn't have dashes; it's just binary data.

You can get the bytes from a Ramsey\Uuid\Uuid object like this:

``` php
$uuid = \Ramsey\Uuid\Uuid::uuid4();
$bytes = $uuid->getBytes();
```

See here, for more information: https://docs.benramsey.com/ramsey-uuid/3.6/class-Ramsey.Uuid.Uuid.html#_getBytes

UUIDs stored in this manner are not sortable, but if you want to use a time-based UUID (version 1) and be able to order by them, you can use the technique described here: https://github.com/ramsey/uuid/wiki/Ramsey%5CUuid-Codec's#store-uuid-in-an-optimized-way-for-innodb-orderedtimecodec

For storing or retrieving from the database, I use `getBytes()` to bind the value to a query parameter for storing to the DB, and I when fetching from the DB, I use `Uuid::fromBytes()` to convert the bytes back to a Uuid object, which I can then use to get a string representation, etc.

**Comment by Yamakasi** [comment]
Yes you are true about the dashed size, sorry for that.

Sounds good! Have you found, or tested, the performance or space using binary ?

About thebinary which doesn't use dashed, you just store a getHex() version ? If so, then I get why the getHex() is in there.

I will go V4 all the way, I don't see a good reason to use V1, V4 is better it seems.

**Comment by ramsey** [comment]
`getBytes()` returns the binary version.

`getHex()` returns a string representation of the UUID; it's just the UUID without dashes.
