### ISSUE TITLE
How to validate name-based and hashed 

### ISSUE THREAD

**Issue by lautiamkok** [ramsey/uuid#181]
How can I validate a name-based hashed has the name that we assign it to the uuid?

```
    // Generate a version 3 (name-based and hashed with MD5) UUID object
    $uuid3 = Uuid::uuid3(Uuid::NAMESPACE_DNS, 'php.net');
    $uuid = $uuid3->toString();
```

For instance:

```
if ($uuid3->getName($uuid) === 'php.net') {
// do something
}
```

Is this possible?

**Comment by jobe1986** [comment]
The only way to validate it successfuly (due to the nature of hashes) would be to re-generate a new UUID of the same version from the same namespace and name. If you don;t know the name that was used then you are out of luck as the concept of the md5 hash (version 3) or the sha1 hash (version 5) is that they are irreversible hashes, that is the same data will always produce the same hash, but you cannot determine the data that was used to produce the hash.
