### ISSUE TITLE
What is the PHP <7.2 incompatibility?

### ISSUE THREAD

**Issue by thumbtech** [ramsey/uuid#248]
Did not see in changelog why dependency bumped to 7.2 and am hoping to cheat on this while lacking a off-the-shelf 7.2 lightsail instance (current = 7.1.20).

Thank you!

**Comment by ramsey** [comment]
The 3.x series has not changed. You may continue to use it on PHP 5.4+. I promoted the master branch to 4.x-dev, which is why you see that there. I haven’t had a 4.x release yet, but there are some BC breaks coming and functionality that relies on PHP 7.2+.

I encourage you to upgrade to PHP 7.2 as soon as you can, though. Both 5.6 and 7.0 are end-of-life in December, and they will no longer receive security updates.

**Comment by ramsey** [comment]
I just realized you said you are on 7.1 (reading/typing from a phone).

PHP 7.1 enters security-fix mode on December 1 of this year, and it will be end-of-life by December of next year. https://secure.php.net/supported-versions.php

I realize that setting the minimum version to 7.2 is going to leave a lot of people behind, but after PHP 7.3, there will likely be no new major language features for a while (until 8.0), so PHP 7.3 is what a lot of libraries are waiting on to target a minimum version in the 7.x series, so be prepared to see many libraries bump their minimum up when 7.3 is released.

**Comment by thumbtech** [comment]
Thanks for quick reply!

Certainly good advice. Not sure you want to bake it in via the package manager, though. Very few of the infrastructure vendors (e.g. Bitnami) have even deployed 7.2 to production at this point.

**Comment by ramsey** [comment]
It’s a good thing I won’t be releasing version 4.x of this library for a while, then. 😀
