### ISSUE TITLE
UuidInterface should declare method __toString() in version 3.x

### ISSUE THREAD

**Issue by Pnoexz** [ramsey/uuid#272]
The `Uuid` class already implements this method as a thin wrapper around `toString()`, however, since it's not declared in the interface, code-quality tools will trigger an error if you type-cast an instance of Uuid to string.

For example, the following code will work

```php
<?php

require_once 'vendor/autoload.php';

echo (string) \Ramsey\Uuid\Uuid::uuid4();
echo PHP_EOL;
```

But phpstan will trigger the following error

```
 ------ -------------------------------------------------- 
  Line   src/uuid_repro.php                                
 ------ -------------------------------------------------- 
  5      Cannot cast Ramsey\Uuid\UuidInterface to string.  
 ------ -------------------------------------------------- 
```

I prefer type casting over calling toString() since, in my opinion, makes the code more readable. Locally, I simply added `public function __toString();` to the interface and the error is no longer reported, but I'm not sure how this will interact with the rest of the library (I'm only using it to generate a uuid4).

**Comment by acasademont** [comment]
Adding this to 3.x would be considered a BC-break, it was already discussed in #111

**Comment by acasademont** [comment]
But it's definitely a PITA and it lookss like 4.x is not coming anytime soon. @ramsey could you consider a 4.0 that's the same as 3.x just with the __toString() method on the interface and then consider all the other changes for 5.x?

**Comment by ramsey** [comment]
I’m currently working to back-port all the non-breaking changes from `master` into `3.x` so that I can do a 3.9 release with those changes and keep moving forward. I’m trying to find the time over the holidays to finish this work, and then I can consider cutting a 4.x release with the interface changes and PHP 7.2 as the lowest required version of PHP.

**Comment by acasademont** [comment]
That would be great, thanks! I believe your model changes deserve a lengthier discussion that I understand can't be done easily

**Comment by ramsey** [comment]
I'm going to go ahead and close this issue. I commented on the PR. For now, the best approach for proper static analysis is to use the `toString()` method, rather than casting. In the 4.x series, I am contemplating whether introducing `__toString()` to the interface makes sense, given the arguments presented in the links on this commit message: https://github.com/ramsey/uuid/commit/feb3eb50d1d216fa720090fc68c704d777c403f6. I will open an issue for discussion.
