### ISSUE TITLE
__toString() in UuidInterface

### ISSUE THREAD

**Issue by kacper-wojtaszczyk** [ramsey/uuid#278]
## The problem

I try to use explicit typecasting to basic types where possible because i find it clearer and more intuitive. With that in mind I always use (string) $uuid for casting the UUIDs to strings. The problem is that the magic method __toString() is only referenced in the actual implementations so when I try to typehint a variable with UuidInterface I get a warning about an unknown method on every cast I made.

## The solution

Add `public function __toString(): string;` to the Interface (happy to make a pull request, just wanted to know if it doesn't break some adopted convention)

## The mic drop

**Comment by ramsey** [comment]
@kacper-wojtaszczyk, thank you for your suggestion. This has been discussed a great deal already. The short answer is that `__toString()` has to wait until a 4.0.0 release, since it's a major BC break to add it to the interface.

Please take a look at the conversations on #272, #238, #111, the discussion at https://github.com/ramsey/uuid/commit/4c467ce4d5a72c3cf0832c813d4d84d222c3d4bb#commitcomment-31174263, and the commit https://github.com/ramsey/uuid/commit/feb3eb50d1d216fa720090fc68c704d777c403f6.

The `__toString()` method is already on UuidInterface in the `4.x` branch, but the comment here has me rethinking that, since the explicitness of `->toString()` has typing and long-term stability benefits: https://github.com/ShittySoft/symfony-live-berlin-2018-doctrine-tutorial/pull/3#issuecomment-460441229

**Comment by kacper-wojtaszczyk** [comment]
Any ETA on 4.0?

**Comment by ramsey** [comment]
No ETA yet. Sorry.
