### ISSUE TITLE
3.x → 4.x upgrade path

### ISSUE THREAD

**Issue by bdsl** [ramsey/uuid#284]
Since this library is [widely used](https://packagist.org/packages/ramsey/uuid/dependents?page=1), and in particular is used by other libraries, it might be worth thinking about how to make it easier for users to upgrade to 4.x. If there is no compatibility with 3.x then all the other libraries that depend on 3.x might make it hard for any given library to decide to upgrade to 4.x

I can see two possible approaches to mitigate this:

* One is to release 4.x under an entirely new name, and using different class name(s) so that it can be installed alongside 3.x in a project. It would be fine to have a dependancy one way or the other between the 4.x and the 3.x

* An other option would be to use similar approach to Symfony, and arrange it so that as near as possible a consumer developed against 4.0 will also be compatible with the last version of 3.x. Consuming packages can declare their compatibility with e.g.`"ramsey/uuid": "^3.4 | ^4"` and be installed alongside other packages that are only compatible with `"^3"`

This follows from some discussion at https://github.com/ramsey/uuid/issues/256#issuecomment-452073875

**Comment by ramsey** [comment]
Thank you for this recommendation!

I have combed the the library as best I can and have written a significant number of tests to ensure that common expected behavior is unaffected. I also decided not to remove everything just yet; rather, I have kept all of the existing methods, but I have marked them as deprecated (I made this change as a direct result of your suggestion).

I've also written a comprehensive upgrade guide to help ease the transition. Please take a look: https://uuid.ramsey.dev/en/latest/upgrading/3-to-4.html

Let me know what you think. Thanks!

**Comment by bdsl** [comment]
Thanks, I haven't had a chance to look at 4.0 in detail yet, but that sounds great. So I guess you'll remove the deprecated methods in 5.0

**Comment by bdsl** [comment]
And the upgrading docs look really good. Hopefully I'll get to do the upgrade at work (from home) before long.

**Comment by ramsey** [comment]
Yes, I’ll remove the deprecated methods in 5.0, which is probably a year or more away.
