### ISSUE TITLE
Error on \Ramsey\Uuid\UuidFactory::uuidFromBytesAndVersion() method

### ISSUE THREAD

**Issue by Olnyov** [ramsey/uuid#365]
## Describe the bug

Then a method Uuid::uuid4()->toString(); used, there is an error intermittently:

`TypeError: unpack() expects parameter 2 to be string, bool given
/vendor/ramsey/uuid/src/UuidFactory.php:477` 

I think there are situations when the string $bytes less than $offset and the substr() function gives a false:

![image](https://user-images.githubusercontent.com/17035466/110074493-5afa9180-7d92-11eb-8638-c22a0c9fc162.png)

Perhaps this is due to the fact that mbstring.func_overload = 2 is installed on the server.

**Comment by ramsey** [comment]
@Olnyov What version of PHP are you using? The `mbstring.func_overload` feature has been deprecated since PHP 7.2.0.

It's possible for me to do a patch that can work around cases when `mbstring.func_overload` is set, but I hesitate to do this, since it's deprecated. For example, I could do something like this:

```php
function binarySubstr(string $bytes, int $offset, ?int $length = null): string
{
    if (extension_loaded('mbstring') && (int) ini_get('mbstring.func_overload') === 2) {
        return mb_substr($bytes, $offset, $length, 'latin1');
    }

    return substr($bytes, $offset, $length);
}
```

I worry about how this would affect performance, though, since it always calls `extension_loaded()`. On many systems, this will be `true`, so then it will also always call `ini_get()`. There are ways to optimize this by doing the checks once and setting some static properties.

I'm interested in hearing from others. This is the first time I've heard of anyone experiencing this problem. If it's affecting more than a few users, I'll consider accommodating environments with `mbstring.func_overload` set.

**Comment by Olnyov** [comment]
Yes, this setting has been deprecated: https://www.php.net/manual/ru/mbstring.overload.php

I think a fix is not needed in this situation. I ask you to close the Issue. For reference, Bitrix CMS has always required mbstring.func_overload = 2. The latest bitrix update no longer requires function overloading. I will update the CMS. Thank you.

**Comment by ramsey** [comment]
Sounds good. Thanks!
