### ISSUE TITLE
Supporting UUID v0

### ISSUE THREAD

**Issue by mrtus** [ramsey/uuid#404]
We've been using UUIDs as encoded version from a key and an integer to obfuscate our auto-increments, to do that we used UUID v0 because that is the only version that has no time encoding.

We used `ramsey/uuid` v3.x and it worked perfectly until we wanted to upgrade to v4.x where version `0` was being returned as `null` and is no longer in the available return values (only v1 to v6) is possible.

Would it be possible to still support v0 UUIDs as well? Or is that something completely out of the question?

Conversion through v3:
```php
    public function encode(string $prefix, int $id, int $version): UuidInterface
    {
        $hash = sha1($prefix . $id);
        $hex = dechex($id);
        $length = strlen($hex);
        $hash = substr($hash, 0, 32 - $length) . $hex;

        $timeHi = BinaryUtils::applyVersion(substr($hash, 12, 4), $version);
        $clockSeqHi = BinaryUtils::applyVariant(hexdec(substr($hash, 16, 2)));

        $fields = [
            'time_low' => substr($hash, 0, 8),
            'time_mid' => substr($hash, 8, 4),
            'time_hi_and_version' => str_pad(dechex($timeHi), 4, '0', STR_PAD_LEFT),
            'clock_seq_hi_and_reserved' => str_pad(dechex($clockSeqHi), 2, '0', STR_PAD_LEFT),
            'clock_seq_low' => dechex($length) . substr($hash, 19, 1),
            'node' => substr($hash, 20, 12),
        ];

        return (new UuidFactory())->uuid($fields);
    }
```

Conversoin through v4:
```php
    public function encode(string $prefix, int $id, int $version): UuidInterface
    {
        $hash = sha1($prefix . $id);
        $hex = dechex($id);
        $length = strlen($hex);
        $hash = substr($hash, 0, 32 - $length) . $hex;

        $timeHi = $this->applyVersion(substr($hash, 12, 4), $version);
        $clockSeqHi = $this->applyVariant(hexdec(substr($hash, 16, 2)));

        $fields = [
            'time_low' => substr($hash, 0, 8),
            'time_mid' => substr($hash, 8, 4),
            'time_hi_and_version' => str_pad(dechex($timeHi), 4, '0', STR_PAD_LEFT),
            'clock_seq_hi_and_reserved' => str_pad(dechex($clockSeqHi), 2, '0', STR_PAD_LEFT),
            'clock_seq_low' => dechex($length) . substr($hash, 19, 1),
            'node' => substr($hash, 20, 12),
        ];

        $hex = vsprintf(
            '%08s-%04s-%04s-%02s%02s-%012s',
            $fields
        );

        return Uuid::fromString($hex);
    }
```

And its usage:
```php
$uuid = $this->encode('<key>', 666, 0);

$uuid->getVersion() // returns null
```

What are your thoughts on this?

**Comment by ramsey** [comment]
What's happening is that you're getting back a "non-standard" UUID (`Ramsey\Uuid\Nonstandard\Uuid`). See here: https://uuid.ramsey.dev/en/stable/nonstandard/other.html

While the example in the documentation shows a `0` returned, this is only because `printf()` with `%d` casts the `null` value to an integer.

This is the code that returns `null`: 

https://github.com/ramsey/uuid/blob/e3e9179f275a44b8e462816d1c65958ff90c4c96/src/Nonstandard/Fields.php#L124-L127

Technically, `null` is correct, since there is no v0 UUID. However, you've defined a v0 UUID for your purposes, and you could create your own `UuidV0` class and your own `VersionZeroUuidBuilder` class that you use to build it. Then, you could create a `new UuidFactory()` and call `setUuidBuilder()` on the factory to give it your custom builder.

This would look something like the example here: https://uuid.ramsey.dev/en/stable/customize/validators.html

I can try to come up with a full example, if this sounds like an approach you would like to take.

**Comment by mrtus** [comment]
@ramsey Thank you for the clear response 👌. I wasn't aware that a `v0` was something that not existing and we might have named it like that ourselves.

We'll take a stab at implementing it as you suggested. Thank you again.
