### ISSUE TITLE
final classes are evil

### ISSUE THREAD

**Issue by hejsan** [ramsey/uuid#50]
Please consider dropping the *final* declaration.
It doesn't seem to serve any practical purpose and makes it harder to integrate the class into our codebase.

Best regards.

**Comment by aztech-dev** [comment]
Have you considered that class inheritance is evil, rather than final is
evil ? :)

**Comment by hejsan** [comment]
Yes and I found that it allows for a flexible experience as opposed to final :)
I do however note that in version 3 the final declaration has been removed, but the codebase seems to have been refactored into oblivion :-\

**Comment by ramsey** [comment]
v3 is still being developed. It is not in oblivion.

**Comment by aztech-dev** [comment]
So final is evil and decoupling is oblivion... I don't want to live in this world :(

**Comment by hejsan** [comment]
Sorry I didn't mean to be offensive, I just get a scare when I see something rather simple turned into a Javaesque soup of interfaces and factories. But then I don't know where you're taking this and it's definitely the best php UUID library I've encountered. :+1:

**Comment by aztech-dev** [comment]
You shouldn't :) The changes do not affect the way the library is consumed at all (Uuid::uuidX() methods work exactly the same as before), and the factory/interface "soup" actually allows consumers to extend functionality without even having to extend the UUID class. Composition, you know... :p

**Comment by ramsey** [comment]
Oh. I misread the equating of decoupling to "oblivion." I thought you meant development has gone into oblivion. It's just slowed down a bit, while I've focused on a few other things.

As for the decoupling being worrisome to you, in the end it will be better for all, since it will allow others to substitute their own PRNGs and more. It will have a lot more flexibility so that many of the things people have been working around will be possible without work-arounds.

**Comment by ramsey** [comment]
Closing this issue, as the `final` class is gone in v3.
