### ISSUE TITLE
Mariadb 10.7+ uuid v7 sort

### ISSUE THREAD

**Issue by fannyfan414** [ramsey/uuid#502]
Hi! Mariadb 10.7+ support [native uuid type ](https://mariadb.com/kb/en/uuid-data-type/). 

But in indexes it rearranges bytes

> UUID are stored in an index friendly manner, the order of a UUID of `llllllll-mmmm-Vhhh-vsss-nnnnnnnnnnnn` is stored as:
> `nnnnnnnnnnnn-vsss-Vhhh-mmmm-llllllll`
> This provides a sorting order, if a UUIDv1 (node and timestamp) is used, of the node, followed by the timestamp.

If I use `uuid v1` and sort `ASC/DESC` - everything is ok. 
But if i use `uuid v7`, then sort is wrong

Is there any possibility to convert uuid v7 to format `llllllll-mmmm-Vhhh-vsss-nnnnnnnnnnnn`?

**Comment by ramsey** [comment]
The UUID datatype in MariaDB appears to expect a version 1 UUID, since it expects the `node` as part of the UUID (i.e., `nnnnnnnnnnnn` part). Since version 7 UUIDs do not contain a node, they will not work with the MariaDB native UUID type.

I recommend you raise this issue with the MariaDB maintainers.
