### ISSUE TITLE
Can I get a collission with UID4 ran on the same system at the same time?

### ISSUE THREAD

**Issue by newtonianb** [ramsey/uuid#61]
I'm using UID4 to generate a random directory as a session folder when HTTP requests come in. 
I understood it uses system timestamps to generate it, but if somehow two requests come in at exactly the same time, would the two UUID4 be different or exactly the same?

**Comment by ramsey** [comment]
UUID version 4 is random. It does not use system timestamps. If your PHP is built with OpenSSL, then this UUID library uses `openssl_random_pseudo_bytes()` to generate random bytes. Otherwise, it uses `mt_rand()`.

UUID version 1 uses system timestamps by taking the microseconds and converting them into a count of 100-nanosecond intervals since the UUID epoch of 1582-10-15 00:00:00. Additionally, it adds a random clock sequence to this number to avoid collisions. It's possible to have a collisions on the same system, but it's unlikely.

**Comment by newtonianb** [comment]
Thank you!
