### ISSUE TITLE
Should we call parent::decode() or $this->decode() in GuidStringCodec?

### ISSUE THREAD

**Issue by ramsey** [ramsey/uuid#74]
Scrutinizer turned up [this issue](https://scrutinizer-ci.com/g/ramsey/uuid/inspections/727c178b-2d1e-43cd-b6a7-c3167f0663a3/issues/files/src/Codec/GuidStringCodec.php?status=existing&orderField=path&order=asc) for [line 54 of GuidStringCodec](https://github.com/ramsey/uuid/blob/3f0ba1ed005a74e650f80eea8352452978b3c4ef/src/Codec/GuidStringCodec.php#L54).

Inside `decodeBytes()`, you call `parent::decode()`, and Scrutinizer wonders if maybe you meant to call `$this->decode()` instead.

At a glance, I wasn't sure whether this was intentional, so I decided to open an issue about it.

**Comment by ramsey** [comment]
@aztech-dev

**Comment by aztech-dev** [comment]
I need to check, but I think it's intentional...

**Comment by aztech-dev** [comment]
I did my homework, I wasn't sure anymore as it's been a while since I wrote the GUID implementation, but basically it boils down to preserving the correct byte order on the first three fields.

I guess you'll have to ignore the issue in Scrutinizer :) I'll open up a P/R over the weekend to add a comment specifying it's intentional and improve the implementation (to handle properly encoding/decoding GUID's based on the endianness of the host).

**Comment by ramsey** [comment]
Great. Thanks!
