### ISSUE TITLE
Serializable Uuid's.

### ISSUE THREAD

**Issue by frankdejonge** [ramsey/uuid#91]
Hi Ben,

I've been using Uuid's instead of incremental ID's for some time now. In some situations I've had to implement the Serializable interface due to output corruption when using regular serialization. An example where this happens is the when an object is stored in native PHP sessions. Would you be open to a PR which makes the Uuid class serializable? My initial thought would be to implement it like this:

```php
public function serialize()
{
    return $this->toString();
}

public function unserialize($serialized)
{
    $uuid = self::fromString($serialized);
    $this->codec = $uuid->codec;
    $this->converter = $uuid->converter;
    $this->fields = $uuid->fields;
}
```

Like the JsonSerializable, the interface could then be added to the UuidInterface. 

Let me know what you think, I'll happily submit a PR with tests.

**Comment by ramsey** [comment]
What is the output corruption you're seeing?

I gave some thought to this when I accepted the JsonSerializable pull request, but I couldn't figure out the value of it, since the behavior would be confusing.

If we serialize it to a string representation of a UUID, what information is available in the serialized representation to tell PHP to unserialize it back into a `Ramsey\Uuid\Uuid` object? It seems to me the engine would see it as a serialized string (despite having an unserialize method on the class) and unserialize it into a PHP string, which is not what I would expect.

If my understanding of how this would work is wrong, let me know.

**Comment by frankdejonge** [comment]
@ramsey the string representation output by the serialize method is used for the output rather than replacing the output, so the output is something like:

```php
"C:16:"Ramsey\Uuid\Uuid":36:{daf8aaf8-be7a-46ed-88ae-41221f36ba11}"
```

So in practice a this:

```php
$oldUuid = Uuid::uuid4();
$uuid = Uuid::fromString($oldUuid->toString());
$oldUuid->equals($uuid); // true
```

Will be the same as:

```php
$oldUuid = Uuid::uuid4();
$uuid = unserialize(serialize($oldUui);
$oldUuid->equals($uuid); // true
```

Hope this clears it up.

**Comment by ramsey** [comment]
Interesting. Please proceed. :-)
